### ISSUE TITLE
Everything should be configurable from filesystem

### ISSUE THREAD

**Issue by svenreimers** [TweetWallFX/TweetwallFX#179]
For faster deployment and integration it is rewuired to configure everything from files living in the filesystem, e.g. etc/..

**Comment by mklaehn** [comment]
Process is ongoing but seeing as `org.tweetwallfx.config.Configuration` allows for configuration via files located on classpath, in the execution directory and the users home. Additionally the order of steps, their configuration and the configuration of their used DataProviders are all possible via Configuration we can close this issue as the adaption to use Configuration instead of hard-coded values can be tracked with separate issue better
